### ISSUE TITLE
sqlConnect.c enhancement

### ISSUE THREAD

**Issue by ChengFu-Ji** [ChengFu-Ji/homework#1]
1. 請 enhence 你的 coding style 以及註解
2. 請實作  strcmp and strncmp

**Comment by IceFire-Fox** [comment]
coding style 及 註解 的部分 可能還需要一點時間
strcmp 及 strncmp 實作 已經於2020/1/24 01:35 
上傳至homework/Sheng/advanced/ 中的 strcmp.c 檔案

**Comment by ChengFu-Ji** [comment]
進階題的部分，請善用字串的特性結尾'\0'，這樣效率會比較好

**Comment by IceFire-Fox** [comment]
是! 我會試試看的
